#!/usr/bin/env python

import localq
import argparse
import sys, os
import Pyro4

__author__ = 'dankle'


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('-j', help="Job ID of job to cancel", action="store", required=True, type=int)
    ap.add_argument('-u', help="URI file path", action="store", required=False, default="~/tmp/localqd", type=str)
    opts = ap.parse_args()

    uri = ""
    urifile = os.path.expanduser(opts.u)
    if os.path.exists(urifile):
        pf = file(urifile, 'r')
        uri = str(pf.read().strip())
        pf.close()
    else:
        print("Could not find file " + str(urifile) + ". Is the localq daemon running?")
        sys.exit(1)

    localqd = Pyro4.Proxy(uri)
    if not localqd.stop_job_with_id(opts.j):
        print("No job with ID " + str(opts.j) + " could be found.")
        sys.exit(1)
    else:
        print("Succesfully killed job " + str(opts.j))

if __name__ == "__main__":
    sys.exit(main())
