#!/usr/bin/env python

import localq
import argparse

__author__ = 'dankle'

ap = argparse.ArgumentParser()
ap.add_argument("command", help="Command to run", choices=["start", "stop"])
ap.add_argument('-n', help="Number of available cores", action="store", required=False, default=1, type=int)
ap.add_argument('-i', help="Time interval (in seconds) to check queue and start jobs", action="store", required=False,
                default=30, type=float)
ap.add_argument('-u', help="URI file path", action="store", required=False, default="~/tmp/localqd", type=str)
ap.add_argument('-p', help="Priority method", choices=["fifo"], default="fifo", type=str)
opts = ap.parse_args()

import sys, os

urifile = os.path.expanduser(opts.u)

daemon = localq.LocalQDaemon(num_cores=opts.n, interval=opts.i, urifile=urifile, priority_method=opts.p)

if opts.command == 'start':
    daemon.start()
elif opts.command == 'stop':
    daemon.stop()
#elif opts.command == 'status':
#    daemon.status()
#elif opts.command == 'restart':
#    daemon.restart()
else:
    ap.print_help()
    sys.exit(2)
sys.exit(0)

