#!/usr/bin/env python
import Pyro4
import sys
import os

__author__ = 'dankle'

usage = """Usage:
    lqueue.py [-u URIFILE]

Options:
  -u URIFILE  file where the uri for the localqd is written
"""


def parse_cli():
    args = sys.argv
    args.pop(0)  # remove script name itself
    cliargs = {'-u': "~/tmp/localqd",
               '-h': None}

    if args:
        while str(args[0]) in cliargs.keys():
            if args[0] == '-h':
                print usage
                sys.exit(1)
            cliargs[args[0]] = args[1]
            args.pop(0)
            args.pop(0)
            if not args:
                break

    return (cliargs, args)


def main():
    (cliargs, cmd) = parse_cli()
    urifile = os.path.expanduser(cliargs["-u"])
    if os.path.exists(urifile):
        pf = file(urifile, 'r')
        uri = str(pf.read().strip())
        pf.close()
    else:
        print "Could not find file " + str(urifile) + ". Is the localq server running?"
        sys.exit(1)

    localqd = Pyro4.Proxy(uri)
    print localqd.list_queue()

if __name__ == "__main__":
    sys.exit(main())
